"""add_platform_to_posts

Revision ID: 909ddffbf606
Revises: 774202e53766
Create Date: 2026-08-02 23:57:13.901773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909ddffbf606'
down_revision: Union[str, None] = '774202e53766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add with a default first so existing rows get backfilled, then drop the default
    op.add_column('posts', sa.Column(
        'platform', sa.String(length=20), nullable=False, server_default='linkedin'
    ))
    op.alter_column('posts', 'platform', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'platform')
    # ### end Alembic commands ###
