"""add_x_tables

Revision ID: b7e0912d409f
Revises: caf13f3b6773
Create Date: 2026-08-03 17:51:29.935041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e0912d409f'
down_revision: Union[str, None] = 'caf13f3b6773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('x_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('handle', sa.String(length=100), nullable=True),
    sa.Column('niche', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('past_tweets', sa.Text(), nullable=True),
    sa.Column('preferred_formats', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('x_threads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('tweets_raw', sa.Text(), nullable=False),
    sa.Column('edited_tweets_raw', sa.Text(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('trend_context', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('copied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_x_threads_batch_id'), 'x_threads', ['batch_id'], unique=False)
    op.create_index(op.f('ix_x_threads_user_id'), 'x_threads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_x_threads_user_id'), table_name='x_threads')
    op.drop_index(op.f('ix_x_threads_batch_id'), table_name='x_threads')
    op.drop_table('x_threads')
    op.drop_table('x_profiles')
    # ### end Alembic commands ###
