"""add_video_tables

Revision ID: caf13f3b6773
Revises: 909ddffbf606
Create Date: 2026-08-03 00:22:02.018843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf13f3b6773'
down_revision: Union[str, None] = '909ddffbf606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_ideas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('angle', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('trend_context', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_ideas_batch_id'), 'video_ideas', ['batch_id'], unique=False)
    op.create_index(op.f('ix_video_ideas_user_id'), 'video_ideas', ['user_id'], unique=False)
    op.create_table('video_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('channel_type', sa.String(length=50), nullable=True),
    sa.Column('niche', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('content_style', sa.Text(), nullable=True),
    sa.Column('past_titles', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_profiles')
    op.drop_index(op.f('ix_video_ideas_user_id'), table_name='video_ideas')
    op.drop_index(op.f('ix_video_ideas_batch_id'), table_name='video_ideas')
    op.drop_table('video_ideas')
    # ### end Alembic commands ###
